// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'QFaARX4e0ZWf7yN5bUG0HQRPCH0-P6GDAySazIA', // AIzaSyADG6P-0HCPRQH0GUb5Ny7fWZ0e4XRAaFQ ESREVER
    appId: '1:969688156232:web:7408e16e2279788734307d',
    messagingSenderId: '969688156232',
    projectId: 'healthtingi-test',
    authDomain: 'healthtingi-test.firebaseapp.com',
    databaseURL: 'https://healthtingi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthtingi-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'wE9ZG1MowByRmwkbYehzGIJWHCbkcdb_BySazIA', //  AIzaSyB_bdckbCHWJIGzheYbkwmRyBwMo1GZ9Ew esREVER
    appId: '1:969688156232:android:127629a41f5b1a4c34307d',
    messagingSenderId: '969688156232',
    projectId: 'healthtingi-test',
    databaseURL: 'https://healthtingi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthtingi-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '0_IED8oE36Tn4CCa5yuBga6g0YD4Xf_BySazIA', //  AIzaSyB_fX4DY0g6agBuy5aCC4ntT63Eo8DEI_0 esREVER
    appId: '1:969688156232:ios:fe8246f503feb82d34307d',
    messagingSenderId: '969688156232',
    projectId: 'healthtingi-test',
    databaseURL: 'https://healthtingi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthtingi-test.firebasestorage.app',
    iosBundleId: 'com.example.heathTingi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '0_IED8oE36Tn4CCa5yuBga6g0YD4Xf_BySazIA', //  AIzaSyB_fX4DY0g6agBuy5aCC4ntT63Eo8DEI_0 esREVER
    appId: '1:969688156232:ios:fe8246f503feb82d34307d',
    messagingSenderId: '969688156232',
    projectId: 'healthtingi-test',
    databaseURL: 'https://healthtingi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthtingi-test.firebasestorage.app',
    iosBundleId: 'com.example.heathTingi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'QFaARX4e0ZWf7yN5bUG0HQRPCH0-P6GDAySazIA', //   AIzaSyADG6P-0HCPRQH0GUb5Ny7fWZ0e4XRAaFQ ESREVER
    appId: '1:969688156232:web:d07ae55cbe62932334307d',
    messagingSenderId: '969688156232',
    projectId: 'healthtingi-test',
    authDomain: 'healthtingi-test.firebaseapp.com',
    databaseURL: 'https://healthtingi-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthtingi-test.firebasestorage.app',
  );
}
